In [2]:
import torch

In [33]:
a = torch.tensor([
    [[[1,2,3],[2,3,4]]],
    [[[2,3,4],[4,5,6]]]

])

print(a.shape) # 2,1,2,3

N, C, W, H = a.size()

b = a.view(N,C,W*H)
print(b)
c = torch.transpose(b, 1, 2)
print(c)
f = b.permute(0,2,1)
print(f)
d = torch.bmm(b,c)
print(d.shape)
print(d)
print(torch.bmm(b,f))

torch.Size([2, 1, 2, 3])
tensor([[[1, 2, 3, 2, 3, 4]],

        [[2, 3, 4, 4, 5, 6]]])
tensor([[[1],
         [2],
         [3],
         [2],
         [3],
         [4]],

        [[2],
         [3],
         [4],
         [4],
         [5],
         [6]]])
tensor([[[1],
         [2],
         [3],
         [2],
         [3],
         [4]],

        [[2],
         [3],
         [4],
         [4],
         [5],
         [6]]])
torch.Size([2, 1, 1])
tensor([[[ 43]],

        [[106]]])
tensor([[[ 43]],

        [[106]]])


In [45]:
a = torch.tensor([
    [[[0,1,2],[10,11,12],[20,21,22]],
    [[0,1,2],[10,11,12],[20,21,22]],
    [[0,1,2],[10,11,12],[20,21,22]]]
])
a.shape

torch.Size([1, 3, 3, 3])

In [78]:
left = a[:,:,:,:-1]
print(left)

tensor([[[[ 0,  1],
          [10, 11],
          [20, 21]],

         [[ 0,  1],
          [10, 11],
          [20, 21]],

         [[ 0,  1],
          [10, 11],
          [20, 21]]]])


In [79]:
right = a[:,:,:,1:]
print(right)

tensor([[[[ 1,  2],
          [11, 12],
          [21, 22]],

         [[ 1,  2],
          [11, 12],
          [21, 22]],

         [[ 1,  2],
          [11, 12],
          [21, 22]]]])


In [84]:
print(right-left)
torch.sum( (right - left)**2 )

tensor([[[[1, 1],
          [1, 1],
          [1, 1]],

         [[1, 1],
          [1, 1],
          [1, 1]],

         [[1, 1],
          [1, 1],
          [1, 1]]]])


tensor(18)

In [80]:
top = a[:,:,:-1,:]
print(top)

tensor([[[[ 0,  1,  2],
          [10, 11, 12]],

         [[ 0,  1,  2],
          [10, 11, 12]],

         [[ 0,  1,  2],
          [10, 11, 12]]]])


In [81]:
bottom = a[:,:,1:,:]
print(bottom)

tensor([[[[10, 11, 12],
          [20, 21, 22]],

         [[10, 11, 12],
          [20, 21, 22]],

         [[10, 11, 12],
          [20, 21, 22]]]])


In [85]:
print(bottom-top)
torch.sum( (bottom - top)**2 )

tensor([[[[10, 10, 10],
          [10, 10, 10]],

         [[10, 10, 10],
          [10, 10, 10]],

         [[10, 10, 10],
          [10, 10, 10]]]])


tensor(1800)