# Part 2 Practices

## How to use torch.sum()

To sum all elements of a tensor:
>torch.sum(outputs) # gives back a scalar

To sum over all rows (i.e. for each column):
>torch.sum(outputs, dim=0) # size = [ncol]

To sum over all columns (i.e. for each row):
>torch.sum(outputs, dim=1) # size = [nrow]

Resource Link
>https://stackoverflow.com/questions/44790670/torch-sum-a-tensor-along-an-axis



In [1]:
import torch
## just simple practice
test_tensor = torch.tensor([[1,2,3],[2,4,6]])
print(test_tensor.shape)
print(torch.sum(test_tensor, dim=0)) # summation of values in the same column
print(torch.sum(test_tensor, dim=1)) # summation of values in the same row


test_denominator = torch.tensor([1,2,3])
print(test_denominator)
print(test_denominator.shape)

# it's different form matrix multiplication
print(test_tensor / test_denominator.view(1,3)) # (2,3) / (1,3) works
# print(test_tensor / test_denominator.view(3,1)) # (2,3) / (3,1) doesn't work

# print(test_tensor.mm(test_denominator.view(1,3))) # (2,3) / (1,3) doesn't work
print(test_tensor.mm(test_denominator.view(3,1))) # (2,3) / (3,1) works


torch.Size([2, 3])
tensor([3, 6, 9])
tensor([ 6, 12])
tensor([1, 2, 3])
torch.Size([3])
tensor([[1, 1, 1],
        [2, 2, 2]])
tensor([[14],
        [28]])


## What is [:] ? 
It means everywhere(e.g. every items in a column, in a row, etc)  
For example, myTensor[:, :] means items in every rows and columns of myTensor  
See more examples below to know other usages

Resource Link
>https://www.cs.virginia.edu/~vicente/recognition/notebooks/python_pytorch_plotting.html

In [14]:
myTensor = torch.tensor([[1,2,3],[2,4,6],[3,6,9]])
print("1. [:, :]")
print(myTensor[:, :]) # 1. all elements
print("")
print("2. [0,0]")
print(myTensor[0, 0]) # 2. first element
print("")
print("3. [:2, :]")
print(myTensor[:2, :]) # 3. first two rows
print("")
print("4. [-2:, :]")
print(myTensor[-2:, :]) # 4. bottom two rows
print("")
print("5. [:, :2]")
print(myTensor[:, :2]) # 5. left two columns
print("")
print("6. [:, -2:]")
print(myTensor[:, -2:]) # 6. right two columns
print("")
print("7. [:2, :2]")
print(myTensor[:2, :2]) # 7. first two rows & right two columns (2X2)

1. [:, :]
tensor([[1, 2, 3],
        [2, 4, 6],
        [3, 6, 9]])

2. [0,0]
tensor(1)

3. [:2, :]
tensor([[1, 2, 3],
        [2, 4, 6]])

4. [-2:, :]
tensor([[2, 4, 6],
        [3, 6, 9]])

5. [:, :2]
tensor([[1, 2],
        [2, 4],
        [3, 6]])

6. [:, -2:]
tensor([[2, 3],
        [4, 6],
        [6, 9]])

7. [:2, :2]
tensor([[1, 2],
        [2, 4]])


## What is '-1' in tensor.view(9, -1) ?
It means that the size -1 is inferred from other dimensions

For example, when a tensor has 3X3 matrix,  
tensor.view[9, -1] will generate [9,1] matrix

Resource Link
>https://pytorch.org/docs/stable/tensors.html?highlight=view#torch.Tensor.view


In [3]:
myTensor = torch.tensor([[1,2,3],[2,4,6],[3,6,9]])
print(myTensor.view(9,-1))
print(myTensor.view(9,-1).shape)

tensor([[1],
        [2],
        [3],
        [2],
        [4],
        [6],
        [3],
        [6],
        [9]])
torch.Size([9, 1])
